# This is a sample _config.yml and can be switched out for another if required

destination: ./_site
include:
  - _pages
collections:
  authors:
    output: true


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Website title
tagline: "Website tagline"
author: Author Name

description: >-
  Website description. 

copyright: "copyright Author name 2020. All rights reserved."
license: "copyright Author name 2020. All rights reserved."

paginate: 5
paginate_path: "/articles/page:num/"

# permalink: /:categories/:title
relative_permalinks: false

timezone: Australia/Brisbane

quiet: false
verbose: false

baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.yourwebsite.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username : https://twitter.com/yourtwitterhandle
github_username : http://github.com/githubusername/
linkedin_username : https://www.linkedin.com/in/linkedinprofile/
medium_username : https://medium.com/@mediumusername
meeting_url: 'https://meetings.hubspot.com/meetingurl'

# GTM Tracking ID
analytics:
  gtm:
    tracking_id: GTM-XXXXXXX

# Build settings
markdown: kramdown
theme: jmblog-theme

# Currently only plugins used that are supported on github pages, though now using netlify so may swap out for pagination v2 in the future
plugins:
- jekyll-gist
- jekyll-mentions
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

kramdown:
  input: GFM



# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# https://staticman-travisdownsio.herokuapp.com/v2/entry/travisdowns/travisdowns.github.io/master/comments
# staticman_url: https://staticmaninstance.herokuapp.com/v2/entry/githubusername/repository/branch/comments

# reCaptcha configuration info: the exact same site key and *encrypted* secret that you used in staticman.yml
# I personally don't think the secret needs to be included in the generated site, but the staticman API bridge uses
# it to ensure the site configuration and bridge configuration match (but why not just compare the site key?)
# reCaptcha:
#   siteKey: yoursitekey
#   secret: yourencryptedsecretkey